language: go
go:
- 1.8
notifications:
  email: false
env:
  global:
    secure: LEa/A2M4NoBOHci2p/UblUNDYjjGZtZ0VxUI7HlXlJfnbU9avJuXffXe7QAk0EhkHJaOHbYMTW/CljCbt6wguevYM1mS2sQGD8ouOyKXkm0ALUADLUV+Q04BmRciLs96WE9t96W+W0/w577JHUv9OrICVVN3BMekYt9LijiPnQI8/7w8j6MhUpnqeGlV/BT2JMjPiUlIbmydW9HNn+moKbXHNNLqlUgVZNUIGFfcLGUrLNbFbl97lZq4KMDMf0G/dz37PAAAhhhgbj7XSybtOG4lB2iNx1J3LdBVkGvAXWTwxJZsdQ03Abda88UdGIkxUc6SqPyRkBDPE30SOVjO9tIQVi9xCtiQ/hpi0hMk3cK9z6sAYSaNRiKNc1HByTh3F1NUmEYhjD4ih53zn+4xyhE86zm7ZIDTwByAPrcG90SGtS5gPTBck+VmymIVmRE9YBgDdEVO5yiutkMO14o2EWvc/ggfRgtMkBQPcRAlyGl8JLigilt33ImR3orptZS52oghRzyUh01s2cDjqKxZ0pp+O6Q/atjW0wIz9PByAx5IyMb9AKZX6C0MRwe9uAii+SHFpQgWLDkrw5MmIIOufZHmZeQ3tr5isC//KX77qTQHH+yoUebrZ5z3KusFCUmxDM0fsLgBSqZUK0Qvh2Q9zuOd4sMTAARciJp73CmnsvI=
